"""empty message

Revision ID: 162d4ffd2e2f
Revises: 
Create Date: 2018-02-13 15:43:54.356529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162d4ffd2e2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('content', sa.String(length=800), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
